on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: List all test branches.
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: PR test action step
        uses: ./ # Uses an action in the root directory
        id: candidates
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          reject-labels: ''
          require-labels: 'test'
          additional-args: '-d'
      # Note -- this doesn't actually work unless you re-run it,
      # because this very test is also running on the PRs, and will
      # get rejected for that reason. So Meta!
      - name: This should list test-branch-2 and test-branch-3
        env:
          mess: ${{ steps.candidates.outputs.branches }}
        run: |
          i=0
          for bla in $mess ; do
            i=$((i+1))
            echo "${i}. ${bla}"
          done
