on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: List all branches that are not on hold, no required label
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: PR test action step
        uses: ./ # Uses an action in the root directory
        id: candidates
      # Use the output from the `hello` step
      - name: print the list of branches, in order.
        env:
          mess: ${{ steps.candidates.outputs.branches }}
        run: |
          i=0
          for bla in $mess ; do
            i=$((i+1))
            echo "${i}. ${bla}"
          done
